x1=int(input("digitar valor de X1  "))
y1=int(input("digitar valor de Y1  "))
x2=int(input("digitar valos de X2  "))
y2=int(input("digitar valor de Y2  "))
d=((x2-x1)**2+(y2-y1)**2)**(1/2)
print("el resultado de d es: ",d)
print(d)